---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  labels:
    app: petclinic
spec:
  replicas: { .Values.count.replicas }
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      imagePullSecrets:
        - name:
            "{ .Values.image.secret_name }"
      containers:
        - name: workload
          image: "{{ .Values.images.image }}:{{ .Values.images.tag }}"
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://{{ .Values.db.host }}:{{ .Values.db.port }}/{{
                .Values.db.name }}
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: create
            - name: SPRING_DATASOURCE_USERNAME
              value:
                "{ .Values.db.username }"
            - name: SPRING_DATASOURCE_PASSWORD
              value:
                "{ .Values.db.password }"
            - name: SPRING_SQL_INIT_MODE
              value:
                "{ .Values.db.SQL_INIT_MODE }"
            - name: SPRING_PROFILES_ACTIVE
              value:
                "{ .Values.db.PROFILES_ACTIVE }"
            - name: SPRING_APPLICATION_JSON
              value: |
                {
                  "management.endpoint.health.probes.add-additional-paths": true
                }
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
              initialDelaySeconds:
                "{ .Values.livenessProbe.initialDelaySeconds }": null
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
              initialDelaySeconds:
                "{ .Values.readinessProbe.initialDelaySeconds }": null
          volumeMounts:
            - mountPath: /bindings/secret
              name: binding
              readOnly: true
      volumes:
        - name: binding
          projected:
            sources:
              - secret:
                  name: demo-db
