---
apiVersion: v1
kind: Service
metadata:
  name: petclinic
spec:
  type:
    "{ .Values.service_app.type }": null
  ports:
    - port:
        "{ .Values.service_app.port }": null
      targetPort:
        "{ .Values.service_app.targetPort }": null
  selector:
    app: petclinic
