
apiVersion: v1
kind: Secret
metadata:
  name: demo-db
type: servicebinding.io/postgresql
stringData:
  type: "postgresql"
  provider: "postgresql"
  host: "{{ .Values.db.host }}"
  port: "{{ .Values.db.port }}"
  database: "{{ .Values.db.name }}"
  username: "{{ .Values.db.username }}"
  password: "{{ .Values.db.password }}"
