images:
  image: 889986388484.dkr.ecr.us-east-1.amazonaws.com/petclinic
  tag: 8
  secret_name: ecr-secret

count:
   replicas: 2

db:
  username: user
  password: pass
  name: petclinic
  host: demo-db
  port: 5432
  SQL_INIT_MODE: never
  PROFILES_ACTIVE: postgres
  praveen: postgres
  tag_db: "15"

livenessProbe:
  initialDelaySeconds: 60

readinessProbe:
  initialDelaySeconds: 60


service_app:
  port: 80
  targetPort: 8080
  type: NodePort 
